<?php
$recipe = [
    'id' => 'chicken-tinola-recipe',
    'title' => 'Chicken Tinola Recipe',
    'author' => 'Vanjo Merano',
    'description' => 'A comforting Filipino soup made with chicken, green papaya, and chili leaves simmered in a savory ginger broth. This hearty dish is perfect for warming up on a chilly day and is often enjoyed with a rice and a condiment of fish sauce and chili pepper on the side.',
    'prep_time' => '10m',
    'cook_time' => '1h',
    'total_time' => '1h 10m',
    'servings' => '6',
    'difficulty' => 'Medium',
    'cuisine' => 'Filipino Recipe',
    'category' => 'Main Course',
    'rating' => 5,
    'rating_count' => 7,
    'image_url' => 'https://panlasangpinoy.com/wp-content/uploads/2018/11/Chicken-Tinola-Soup-Recipe.jpg',
    'ingredients' => [
        '3 lbs. chicken (cut into serving pieces)',
        '2  green papaya (wedged)',
        '1 ½ cup malunggay leaves',
        '1 cup hot pepper leaves',
        '5 cloves garlic (crushed and chopped)',
        '1  onion (chopped)',
        '3 thumbs  ginger (julienne)',
        '2  Maggi Magic Chicken Cubes',
        '1 quart rice wash (See notes)',
        '1 quart water',
        '2 tablespoons fish sauce',
        'Ground black pepper to taste (optional)',
        '3 tablespoons cooking oil',
    ],
    'instructions' => [
        'Heat cooking oil in a cooking pot. Sauté garlic, onion, and ginger until the onion softens.',
        'Add the chicken. Continue sautéing for 2 minutes or until it turns light brown in color.',
        'Pour 2 tablespoons of fish sauce. Stir.',
        'Add the rice wash into the cooking pot. Let it boil. Simmer for 10 minutes.',
        'Add water as needed. Let it boil.',
        'Put the green papaya wedges into the pot. Continue to simmer for 15 to 20 minutes.',
        'Add Maggi Magic Chicken Cubes. Stir. Season with ground black pepper (this is optional). Turn off the heat and then add the hot pepper leaves and malunggay leaves into the cooking pot. Cover for 2 minutes to let the residual heat cook the green veggies.',
        'Transfer to a serving bowl. Serve. Share and enjoy!',
    ],
    'nutrition' => [
        'servingSize' => '6 g',
        'calories' => '662 kcal',
        'carbohydrateContent' => '21 g',
        'proteinContent' => '47 g',
        'fatContent' => '42 g',
        'saturatedFatContent' => '10 g',
        'cholesterolContent' => '170 mg',
        'sodiumContent' => '651 mg',
        'fiberContent' => '2 g',
        'sugarContent' => '9 g',
        'transFatContent' => '0.2 g',
        'unsaturatedFatContent' => '28 g',
    ]
];

include dirname(__FILE__) . '/../recipe-template.php';
?>